language: java

script: ./bin/run_tests.sh

notifications:
  email:
    recipients:
      - greenbutton-dev@googlegroups.com
    on_success: always

branches:
  only:
    - master

after_success:
- bash <(curl -s https://codecov.io/bash)
