# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Primary container image where all commands run
      - image: circleci/openjdk:8-jdk
        environment:
          DATACUSTODIAN_DB_URL: jdbc:mysql://localhost:3306/datacustodian
          THIRDPARTY_DB_URL: jdbc:mysql://localhost:3306/thirdparty
          TOKENSTORE_DB_URL: jdbc:mysql://localhost:3306/tokenstore
          DB_DRIVER: com.mysql.cj.jdbc.Driver
          DB_ROOT_USER: root
          DB_PASSORD: 'password'

    # Service container image
      - image: circleci/mysql:8.0.20
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Wait for MySQL Database Connection
          # Preinstalled in circleci/* docker image
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Update CircleCI image
          command: sudo apt-get update

      - run:
          name: Install default-mysql-client
          command: sudo apt-get install default-mysql-client

      - run:
          name: Create thirdparty database
          command: |
            mysql -h 127.0.0.1 -u user -ppassw0rd thirdparty < etc/cleandatabases_tp.sql
            mysql -h 127.0.0.1 -u user -ppassw0rd thirdparty < etc/prepopulatesql_tp.sql
            mysql -h 127.0.0.1 -u user -ppassw0rd thirdparty < etc/prepopulatesql_users_tp.sql
            mysql -h 127.0.0.1 -u user -ppassw0rd --execute="SELECT * FROM thirdparty.retail_customers"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test
      - run: mvn sonar:sonar -Dsonar.projectKey=GreenButtonAlliance_OpenESPI-Common-java -Dsonar.organization=greenbuttonalliance -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=2faf1894b56ac6eed24be5df05f34072fce3748b